### PR TITLE
1.12.2 non-critical updates and stuff

### PR DESCRIPTION
**Pull request by magneticflux-**
I updated the Forge version, the MCP mappings, and the Gradle wrapper, I added a `.gitignore` and recommended IDEA project files, and I added a Travis CI config that builds and runs the `check` task on each commit.

### CODE REVIEW

**Comment by univrsal** [comment]
Does the .idea folder contain any crucial files? Because I wouldn't want it in the repository unless it served a purpose

**Comment by magneticflux-** [comment]
JetBrains themselves recommend that the folder is checked in [here](https://intellij-support.jetbrains.com/hc/en-us/articles/206544839):

> All the files under .idea directory in the project root **except** the workspace.xml, usage.statistics.xml, and tasks.xml files which store user specific settings

They also maintain a `.gitignore` for JetBrains projects [here](https://github.com/github/gitignore/blob/master/Global/JetBrains.gitignore) that follows their guidelines. Right now the files just have empty config options in them for the most part, but it checking them in makes sure developers have a consistent view of the project.

Additionally, since the project is imported from a Gradle project, the `.iml` files are ignored on [these lines](https://github.com/github/gitignore/blob/master/Global/JetBrains.gitignore#L27-L33) (uncommented in this PR).

**Comment by univrsal** [comment]
Well, thanks again for your contribution

**Comment by magneticflux-** [comment]
@univrsal 😄 If you want to get CI working, just set up the [Travis Ci GitHub app](https://github.com/marketplace/travis-ci)!

**Comment by univrsal** [comment]
Don't think that's necessary for a project this small

**Pull request merged**
